services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: golang-api
    restart: unless-stopped
    volumes:
      - ./data/uploads:/app/uploads
    environment:
      - PORT=8080
      - UPLOAD_DIR=/app/uploads
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./data/uploads:/usr/share/nginx/uploads:ro
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge